// <auto-generated />
using System;
using DatabasFinal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabasFinal.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20210119134920_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DatabasFinal.Models.TempIndoor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<double>("IndoorTemp")
                        .HasColumnType("float");

                    b.Property<double>("MouldRisk")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TempsIndoor");
                });

            modelBuilder.Entity("DatabasFinal.Models.TempOutdoor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<double>("IndoorTemp")
                        .HasColumnType("float");

                    b.Property<double>("MouldRisk")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TempsOutdoor");
                });
#pragma warning restore 612, 618
        }
    }
}
